# ====   Copyright 2026, mCoDev Systems, All rights reserved.   ====
# =  Purpose:    docker-compose file,   describes the container.
# =  Reference:  
# =  Author:     Steve (Sev) Mathot, mCoDev Systems. (www.mcodev.net)
# =  License:    mCoDev Systems General Public License (MIT)
# =  Usage:      docker-compose up [-d]
# =  Output:     
# ==================================================================

# Before running docker-compose, make sure the folder data exists + the JSON files in that folder.
# While the container is starting, check the logs. Hytale Server will require authentication!

services:
  hytale-server:
    image: mcodev-hytale-server:main
    container_name: mcodev_hytale_server
    restart: unless-stopped
    ports:
      - "5520:5520/udp"
    volumes:
      - ./data/bans.json:/app/Server/bans.json:rw
      - ./data/config.json:/app/Server/config.json:rw
      - ./data/permissions.json:/app/Server/permissions.json:rw
      - ./data/whitelist.json:/app/Server/whitelist.json:rw
      - ./data/backups:/app/Server/backups:rw
      - ./data/logs:/app/Server/logs:rw
      - ./data/mods:/app/Server/mods:rw
      - ./data/universe:/app/Server/universe:rw

